<?php
// This file was generated by running "composer dump-env prod"
return [
    'APP_ENV'           => 'prod',
    'APP_SECRET'        => '11111111111111111111111111111111',
    'DATABASE_SERVER'   => 'prod_host',
    'DATABASE_USER'     => 'prod_user',
    'DATABASE_PASSWORD' => 'prod_password',
    'DATABASE_NAME'     => 'prod_database',
    'DATABASE_URL'      => 'mysql://dev_user:dev_password@dev_host:3306/dev_database',
];
